### ISSUE TITLE
phy2str.pl error

### ISSUE THREAD

**Issue by ChenqCQ** [smussmann82/file_converters#1]
Hi stevemussmann,
Thank you very much for providing so useful scripts.

I used phy2str.pl to convert .phy file to .str, but happend running error: 
File "/TA1/liu/cg/su_analysis/convertfile/file_convert/file_converters-master/phy2str.pl", line 3
    use warnings;
               ^
SyntaxError: invalid syntax
yhrun: error: cn7366: task 0: Exited with exit code 1

my command is: python /TA1/liu/cg/su_analysis/convertfile/file_convert/file_converters-master/phy2str.pl -p /TA1/liu/cg/su_analysis/convertfile/resultes/vcftophy/C4.phy -o phytostr

I don't understand what the mistake was, my .phy file was converted using the vcf2phylip by you recommended. Do you know what happend?

**Comment by stevemussmann** [comment]
Hello,

I think the problem is that you tried to call phy2str.pl as a python script, but it is actually a perl script. Change 'python' in your command to 'perl' and it should work.

-Steve
